---
- name: Validate MinIO role inputs
  ansible.builtin.import_tasks: validate.yml

- name: Install MinIO prerequisites
  ansible.builtin.package:
    name: "{{ anro_minio_packages }}"
    state: present

- name: Install MinIO server
  ansible.builtin.import_tasks: install-server.yml
  when: anro_minio_install_server | bool

- name: Install MinIO client
  ansible.builtin.import_tasks: install-client.yml
  when: anro_minio_install_client | bool

- name: Wipe MinIO data directories
  ansible.builtin.import_tasks: wipe-drives.yml
  when:
    - anro_minio_wipe_all_drives | bool
    - anro_minio_wipe_all_drives_confirm | bool

- name: Configure MinIO server
  ansible.builtin.import_tasks: configure-server.yml
  when:
    - anro_minio_install_server | bool
    - anro_minio_configure_server | bool
