---
# when starting fresh its nice to just wipe all the drives
# be careful when using this all data will be wiped
- name: Initiate drive wipe drives
  ansible.builtin.include_tasks: wipe-drives.yaml
  when:
    - anro_minio_wipe_all_drives is defined
    - anro_minio_wipe_all_drives | bool

- name: Install minio Server
  ansible.builtin.include_tasks: install-server.yaml
  when:
    - anro_minio_install_server | bool

- name: Configure minio server
  ansible.builtin.include_tasks: configure-server.yaml
  when:
    - anro_minio_configure_server | bool

- name: Install minio client
  ansible.builtin.include_tasks: install-client.yaml
  when:
    - anro_minio_install_client | bool

- name: Cleanup
  ansible.builtin.include_tasks: cleanup.yaml
  when:
    - anro_minio_install_client | bool
