---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart MinIO
  ansible.builtin.systemd_service:
    name: "{{ anro_minio_server_service }}"
    state: restarted
  when: anro_minio_configure_server | bool
