---
- name: Install MinIO
  hosts: minio
  become: true
  roles:
    - role: anro_minio
      vars:
        anro_minio_root_user: "{{ vault_anro_minio_root_user }}"
        anro_minio_root_password: "{{ vault_anro_minio_root_password }}"
        anro_minio_server_datadirs:
          - /srv/minio/data
