---
- name: Install MinIO
  hosts: minio
  become: true
  roles:
    - role: anro_minio
      vars:
        minio_root_user: "{{ vault_minio_root_user }}"
        minio_root_password: "{{ vault_minio_root_password }}"
        minio_server_datadirs:
          - /srv/minio/data
